Implement CSS for the page Fashion Home - 1
st-minhho/FE-Internship-Summer-2022_st-minhho_FE-Exercise pull request #5
Opened 2022-06-10 16:03 UTC by st-minhho

### Reference
- [Design ](https://www.figma.com/file/CUQiZbPKOlfjHZn9hBqrPh/Fashion?node-id=0%3A1)

### Descriptions
> **Implement CSS for header, .section-banner, .banner-policy.**
> ![image](https://user-images.githubusercontent.com/106951920/173103239-e50f3167-ce82-4272-8be1-09b6520b3f4e.png)

### Checklist
- [x] The code has been built and tested in the local environment.
- [ ] All basic bugs have been found and fixed.

2022-06-13 15:29 UTC, st-quangnguyen2 requested changes

2022-06-13 16:53 UTC, st-duynguyen commented on index.css
> +
Remove dòng trống

2022-06-13 16:58 UTC, st-duynguyen commented on index.css
> +  margin-left: -10px;
Dùng shorthand nha e. Ex: `margin: 0 -10px;`

2022-06-13 16:58 UTC, st-duynguyen commented on index.css
> +  padding-left: 10px;
Dùng shorthand nha e

2022-06-13 17:00 UTC, st-duynguyen commented on index.css
> +.overlay {
overlay này em chuyển sang dùng pseudo after nghe

2022-06-13 17:03 UTC, st-duynguyen commented on index.css
> +  font-weight: 300;
Nên gộp những thuộc tính chung loại lại với nhau. Ex:
```
font-weight: 300;
font-size: 32px;
line-height: 48px;
text-align: center;

2022-06-13 17:04 UTC, st-duynguyen commented on index.css
> +  font-size: 18px;
Tương tự, nên gọp những thuộc tính giống nhau lại, check lại tất cả cho những thằng khác

2022-06-13 17:06 UTC, st-duynguyen commented on index.css
> +  height: 800px;
Bị trùng set height 800px cho banner, chỉ nên set cho thằng section-banner

2022-06-13 17:10 UTC, st-duynguyen commented on index.css
> +.banner-policy {
Check lại css phần này, đang bị sai so với design
![Screen Shot 2022-06-14 at 12 11 15 AM](https://user-images.githubusercontent.com/62866904/173407913-a06dd8f3-86e4-4cf2-b940-ecaff060df5a.png)

2022-06-13 17:13 UTC, st-duynguyen commented on index.css
> +.badge-blog {
Check lại font-size của thằng badge. Trong design đang là 12px thôi

2022-06-13 17:16 UTC, st-duynguyen commented on index.css
> +.policy-item:nth-child(2) .policy-title {
Không nên css kiểu vậy mà nên khai báo thêm 1 class là policy-active chả hạn để handle

2022-06-13 17:17 UTC, st-duynguyen commented on index.css
> +.price-original {
Sai màu so với design

2022-06-13 17:20 UTC, st-duynguyen commented on index.html
> +        <div class="footer-left">1
Dư số 1 ở chỗ này

2022-06-13 17:22 UTC, st-duynguyen commented on index.css
> +  position: relative;
Viết chung lại 1 class cho những thuộc tính dùng chung, chỉ đặt class riêng để handle cho background-image thôi nha e

2022-06-13 17:23 UTC, st-duynguyen commented on index.css
> +@import url("https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;700&display=swap");
đặt lại tên file là style.css

2022-06-13 17:25 UTC, st-duynguyen commented on index.css
> +.blog-overlay {
Tất cả những thằng overlay e sửa lại dùng after nha

2022-06-13 17:26 UTC, st-duynguyen commented on index.css
> +.form-subscribe .row {
đặt thêm tên class cho nó, k được css vào thằng row

2022-06-13 17:27 UTC, st-duynguyen commented on index.css
> +  color: var(--white);
Đối với những loại text hay dùng trong page, e nên đặt thêm 1 class common là text-primary, text-secondary để tiện dùng, k nên đụng tới text nào thì css cho text đó

2022-06-13 17:30 UTC, st-duynguyen requested changes
@st-minhho Check comment của a nghe

2022-06-14 07:59 UTC, st-duynguyen approved these changes
@st-minhho  A sẽ review kĩ ở PR sass. H a merge để e làm bài tập sass nha.

2022-06-14 07:59 UTC, merged